tracing:
  samplingRate: "1"
  zipkin:
    #endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
    endpointAddress: "http://zipkin:9411/api/v2/spans"
metrics:
  enabled: true

