services:
  spotifyfrontend:
    image: spotify/frontend
    container_name: spotifyfrontend
    build:
      context: .
      dockerfile: Frontend/SpotifyFrontend.Web/Dockerfile
  
  spotifyfrontend-dapr:
    container_name: spotifyfrontend-dapr
    image: "daprio/daprd:1.5.1"
    network_mode: "service:spotifyfrontend"
    depends_on:
      - spotifyfrontend

  spotifybackend:
    image: spotify/backend
    container_name: spotifybackend
    build:
      context: .
      dockerfile: Gateways/SpotifyBackend/Dockerfile
    depends_on:
      - redis
  
  spotifybackend-dapr:
    container_name: spotifybackend-dapr
    image: "daprio/daprd:1.5.1"
    network_mode: "service:spotifybackend"
    depends_on:
      - spotifybackend
    
  albums:
    image: spotify/albums
    container_name: albums
    build:
      context: .
      dockerfile: APIs/SpotifyAlbums.WebApi/Dockerfile
    depends_on:
      - spotifybackend
      - redis

  albums-dapr:
    container_name: albums-dapr
    image: "daprio/daprd:1.5.1"
    network_mode: "service:albums"
    depends_on:
      - albums
    
  artists:
    image: spotify/artists
    container_name: artists
    build:
      context: .
      dockerfile: APIs/SpotifyArtists.WebApi/Dockerfile
    depends_on:
      - spotifybackend
      - redis

  artists-dapr:
    container_name: artists-dapr
    image: "daprio/daprd:1.5.1"
    network_mode: "service:artists"
    depends_on:
      - albums
    
  songs:
    image: spotify/songs
    container_name: songs
    build:
      context: .
      dockerfile: APIs/SpotifySongs.WebApi/Dockerfile
    depends_on:
    - spotifybackend
    - redis

  songs-dapr:
    container_name: songs-dapr
    image: "daprio/daprd:1.5.1"
    network_mode: "service:songs"
    depends_on:
      - songs

# Components
  #Pub-Sub & State
  redis:
    container_name: redis
    image: redis:alpine

  # Observability
  #zipkin:
  #  container_name: zipkin
  #  image: openzipkin/zipkin-slim

  jeager:
    container_name: jeager
    image: jaegertracing/all-in-one:1.29
    environment:
        - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
        - 5775:5775
        - 6831:6831
        - 6832:6832
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 14250:14250
        - 9411:9411
# Components