apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demosecrets
  namespace: default
spec:
  type: secretstores.local.file
  metadata:
    - name: secretsFile
      value: components/secrets.json
    - name: nestedSeparator
      value: ":"